import type { Metadata } from "next";
import "./globals.scss";
import Header from "@/components/sections/header/header";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="overflow-auto">
				<Header />
				{children}
			</body>
    </html>
  );
}
